# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    # tags:
    #   - v*
    branches: [ "dev-0.3.6-ezreal", "main" ]
  # pull_request:
  #   branches: [ "dev-0.3.6-ezreal", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: yarn install
      - run: yarn build
      - name: '缓存 Cache'
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/yarn.lock')}}
      - name: '读取当前版本号 Read the current version number'
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: version
      - name: echo artifact
        run: |
          echo ${{ steps.version.outputs.value }}
          echo github ${{ github }}
          echo github.sha ${{ github.sha }}
          echo github.ref ${{ github.ref }}
          echo github.title ${{ github.title }}
      - name: Create GitHub Release
        id: 创建 create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.value  }}-alpha
          release_name: release ${{ steps.version.outputs.value  }}-alpha
          draft: false
          prerelease: false
      - name: 归档 Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'tar'
          path: './build'
          filename: linux-all-casaos-v${{ steps.version.outputs.value }}-alpha.tar.gz
      - name: 上传 Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linux-all-casaos-v${{ steps.version.outputs.value }}-alpha.tar.gz
          asset_name: linux-all-casaos-v${{ steps.version.outputs.value }}-alpha.tar.gz
          asset_content_type: application/zip
      - name: 刷新缓存 Refresh The Cache
        run: |
          curl https://purge.jsdelivr.net/npm/iemotion-pic@latest/dist/name.json

