name: push_test_server

on:
    push:
        branch:
            - feature*
    workflow_dispatch:

jobs:
    release:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 16.x ]
            # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            -   uses: actions/checkout@v3
            -   name: '使用 Use Node.js ${{ matrix.node-version }}'
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: 'npm'
            -   name: '缓存 Cache'
                uses: actions/cache@v3
                id: cache-dependencies
                with:
                    path: node_modules
                    key: ${{runner.OS}}-${{hashFiles('**/yarn.lock')}}

            -   name: install git
                run: sudo apt install --yes git

            -   name: git global
                run: sudo git config --global --add safe.directory '*'

            -   name: Fetch all tags
                run: sudo git fetch --force --tags

            -   name: Get version
                id: get_version
                # run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
                run: echo "VERSION=$(git describe --abbrev=0 --tags | awk -F- '{print $1}')" >> $GITHUB_ENV
                # run: echo "VERSION=v99.99.99" >> $GITHUB_ENV

            -   name: show version
                id: show_version
                run: echo ${{ env.VERSION }}
                # run: echo ${{ steps.get_version.outputs.VERSION }}

            -   run: corepack prepare yarn@3.5.1 --activate
            -   run: yarn
            -   run: yarn build
            -   run: |
                    tar -zcvf linux-all-casaos-v99.99.99.tar.gz build
                    ls

            -   name: install sshpass
                run: sudo apt install sshpass --yes


            -   name: ZeroTier
                uses: zerotier/github-action@v1.0.1
                with:
                    network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
                    auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

            -   name: ping hostname
                shell: bash
                run: |
                    count=10
                    while ! ping -c 1 10.147.18.11 ; do
                      echo "waiting..." ;
                      sleep 1 ;
                      let count=count-1
                    done
                    echo "ping success"

            -   name: copy tar to target hostname
                shell: bash
                run: |
                    sshpass -p "${{ secrets.ssh_password }}" scp -r -o StrictHostKeyChecking=no -P 22 ./linux-all-casaos-v99.99.99.tar.gz root@10.147.18.11:/var/www/download
                    echo "ping success"
            -   name: send message
                run: |
                    curl -X POST -H "Content-Type: application/json" -d '{"msg_type":"text","content":{"text":"CasaOS-UI updated ${{ env.VERSION }}"}}'  https://open.feishu.cn/open-apis/bot/v2/hook/eb8f45c7-9636-4b64-84f2-a66d9aeb9d30
